// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL as string | undefined) ?? undefined;
const SUPABASE_PUBLISHABLE_KEY =
      (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined) ?? undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Make env/config issues obvious (especially in deployed builds).
// Without this, missing env vars often looks like "INCORRECT API KEY".
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      // eslint-disable-next-line no-console
      console.error('Missing Supabase env vars', {
              VITE_SUPABASE_URL: !!SUPABASE_URL,
              VITE_SUPABASE_PUBLISHABLE_KEY: !!SUPABASE_PUBLISHABLE_KEY,
      });
      throw new Error(
              'Supabase is not configured. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in your Vercel Environment Variables and redeploy.'
            );
}

// eslint-disable-next-line no-console
console.log('SUPABASE INIT', {
      url: SUPABASE_URL,
      keyLength: SUPABASE_PUBLISHABLE_KEY.length,
});

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
              storage: localStorage,
              persistSession: true,
              autoRefreshToken: true,
      },
});
Page_Down// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL as string | undefined) ?? undefined;
const SUPABASE_PUBLISHABLE_KEY =
    (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined) ?? undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Make env/config issues obvious (especially in deployed builds).
// Without this, missing env vars often looks like "INCORRECT API KEY".
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    // eslint-disable-next-line no-console
    console.error('Missing Supabase env vars', {
          VITE_SUPABASE_URL: !!SUPABASE_URL,
          VITE_SUPABASE_PUBLISHABLE_KEY: !!SUPABASE_PUBLISHABLE_KEY,
    });
    throw new Error(
          'Supabase is not configured. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in your Vercel Environment Variables and redeploy.'
        );
}

// eslint-disable-next-line no-console
console.log('SUPABASE INIT', {
    url: SUPABASE_URL,
    keyLength: SUPABASE_PUBLISHABLE_KEY.length,
});

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
          storage: localStorage,
          persistSession: true,
          autoRefreshToken: true,
    },
});// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
